import { getAllSchemaDescriptions } from '@/agent/toolSpecSchemas';
import type { ToolSpecInputV2, DataType } from '@/agent/toolSpecSchemas';

/**
 * System prompt for the agent (V2 - uses tools)
 */
export function buildSystemPrompt(): string {
  const schemaDescriptions = getAllSchemaDescriptions();
  
  return `
You are an expert at creating database query tool specifications. Use the tools provided to inspect schema and sample data.

CRITICAL: Your final response MUST be a JSON object with this exact structure:
{
  "toolSpec": {
    // Complete tool specification object
  },
  "explanation": "optional - summary of the execution"
}

The "toolSpec" field must contain a complete tool specification with ALL required fields.

${schemaDescriptions}

IMPORTANT RULES FOR toolSpec:
- If dataType is "collection", include "collection_name" and omit "table_name"
- If dataType is "table", include "table_name" and omit "collection_name"
- CRITICAL: "parameters" MUST be an ARRAY of objects, NOT an object with keys. Each parameter object must follow the ToolParameter schema above
- Only include partition keys, sorting keys, and indexed columns as parameters
- Partition keys are mandatory parameters
- For indexed date/time or timestamp parameters, generate start_<column_name> and end_<column_name> parameters using $gt and $lte operators
- For indexed numeric parameters, generate min_<column_name> and max_<column_name> parameters using $gte and $lte operators
- If a column is a vector column, generate the embedding_model as text-embedding-3-small
- Include "info" field explaining why each parameter was considered (e.g., "it is an indexed column", "it is a partition key")
- The explanation field should provide a summary of the execution
- The paramMode should be always tool_param, which indicates that its value will be generated by the agent. Use static or expression only if the user asked for a condition that will not be controlled by the agent.
- - E.g: The user asked to add a filter for future dates, then use a python expression using the datetime library iand the operator $gte.
- - E.g: The user asked for records where a field has the value "John", then use a static value and the operator $eq.
`;
}

/**
 * User prompt template for the agent (V2)
 */
export function buildAgentPrompt(input: ToolSpecInputV2): string {
  const userPrompt = input.prompt?.trim() || 'No additional instructions provided.';
  const existingSpec =
    input.existingToolSpec && Object.keys(input.existingToolSpec).length > 0
      ? JSON.stringify(input.existingToolSpec, null, 2)
      : '';

  return `

User Request:
${userPrompt}

${existingSpec ? `Existing Tool Spec (update this based on the new request):\n${existingSpec}\n` : ''}

Target ${input.dataType}: ${input.name}
Database: ${input.dbName || 'default'}

`;
}

/**
 * Structured output prompt for final tool spec generation (V2)
 */
export function buildStructuredOutputPrompt(): string {
  return `Based on the information gathered and validation performed, generate the tool specification response.

CRITICAL STRUCTURE REQUIREMENT:
You MUST return a JSON object with this EXACT structure - do NOT return just a tool spec, it MUST be wrapped:
{
  "toolSpec": {
    // Complete tool specification object with ALL required fields
  },
  "explanation": "string" // OPTIONAL - summary of the execution
}

The "toolSpec" field is REQUIRED and must contain a complete tool specification object.
The "explanation" field is OPTIONAL and returns a summary of the execution.

${getAllSchemaDescriptions()}

Remember for the toolSpec object inside "toolSpec":
- If dataType is "collection", include "collection_name" and omit "table_name"
- If dataType is "table", include "table_name" and omit "collection_name"
- Must include all required fields as specified in the ToolSpec schema above
- CRITICAL: "parameters" MUST be an ARRAY, not an object. Each parameter must follow the ToolParameter schema above. Example format:
  "parameters": [
    {
      "param": "customer_id",
      "paramMode": "tool_param",
      "type": "string",
      "description": "Customer ID",
      "attribute": "customer_id",
      "operator": "$eq",
      "required": true,
      "info": "it is a partition key"
    }
  ]
- Follow all the IMPORTANT RULES from the system prompt`;
}

/**
 * System message for tool spec generation (V1 - direct OpenAI)
 */
export const SYSTEM_MESSAGE_V1 = 'You are an expert at creating database query tool specifications. Always return valid JSON only, no markdown formatting.';

/**
 * Main prompt template for tool spec generation (V1 - direct OpenAI)
 */
export function buildToolSpecPromptV1(params: {
  dataType: DataType;
  name: string;
  dbName?: string;
  userPrompt?: string;
  existingSpec?: string;
  tableDefinition?: string;
  attributes: string[];
  sampleData: any[];
}): string {
  const {
    dataType,
    name,
    dbName,
    userPrompt,
    existingSpec,
    tableDefinition,
    attributes,
    sampleData,
  } = params;

  const tableSpecificRules = dataType === 'table' ? `
IMPORTANT: Consider ONLY the partition keys, sorting keys and indexed columns as parameteres.
IMPORTANT: Partition keys are mandatory parameters.
IMPORTANT: For indexed date time or timestamps parameters, generate start_<column_name> and end_<column_name> parameters. use $gt and $lte operators.
IMPORTANT: For indexed numeric parameters, generate min_<column_name> and max_<column_name> parameters. use $gte and $lte operators.
IMPORTANT: If the column is a vector column, generate the embedding_model as text-embedding-3-small.
` : '';

  return `
You are an expert at creating database query tool specifications. Based on the following ${dataType} structure and sample data, generate a comprehensive tool specification in JSON format.
      
You are given a table schema  or collection attributes and sample data.
You need to generate a tool specification for the data object.
The tool specification should be in the format of a JSON object.
While generate descriptions, define it in a way to make it easier for LLM to understand it.
Use the sample data to identify data types, patterns and enums.

${tableSpecificRules}

IMPORTANT: Return ONLY valid JSON without any markdown formatting, code blocks, or additional text.

${tableDefinition ? `Table schema (columns, partition keys, sort keys):\n${tableDefinition}\n` : ''}
User Request:
${userPrompt ? userPrompt : 'No additional instructions provided.'}

${existingSpec ? `Existing Tool Spec (update this based on the new request):\n${existingSpec}\n` : ''}

${dataType} Name: ${name}
Available Attributes: ${attributes.join(', ')}

Sample Documents (first 5):
${JSON.stringify(sampleData, null, 2)}

Generate a tool specification JSON with the following structure:
{
  "name": "descriptive_tool_name",
  "description": "Clear description of what this tool does",
  "type": "tool",
  "method": "find",
  "${dataType === 'collection' ? 'collection_name' : 'table_name'}": "${name}",
  "db_name": "${dbName || 'default'}",
  "parameters": [
    {
      "param": "parameter_name",
      "paramMode": "tool_param",
      "type": "string|number|boolean|timestamp|float|vector",
      "description": "Parameter description",
      "attribute": "attribute_name_from_list",
      "operator": "$eq|$gt|$gte|$lt|$lte|$in|$ne",
      "required": true|false
      "info: "Why the parameters was considered, eg: it is an indexed column, a partition key or any other reason."
    }
  ],
  "projection": {
    "attribute_name": 1,
  },
  "limit": 10,
  "enabled": true,
  "tags": ["relevant", "tags"]
}

Return ONLY valid JSON, no markdown, no explanations.`;
}
